name: Netlify Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm install fs-extra
          echo "Dependencies installed successfully"

      - name: Prepare 3D Model Placeholders
        run: |
          node copy-models.js || {
            echo "Copy models script failed"
            exit 1
          }

      - name: Lint Code
        continue-on-error: true
        run: npm run lint

      - name: Build Project
        run: |
          npm run build
          echo "Build completed successfully"
          ls -lR dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Create Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
          retention-days: 5

      - name: Final Status Check
        if: always()
        run: |
          echo "Deployment workflow completed. Check previous steps for detailed logs."
